

headers = {1:{
  "Content-Type":"application/json",
  "Accept":"*/*",
  "Accept-Language":"en-US,en;q=0.9",
  "Accept-Encoding":"gzip, deflate, br",
  "Host":"apionline.homedepot.com",
  "Origin":"https://www.homedepot.com",
  "User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15",
  "Connection":"keep-alive",
  "Referer":"https://www.homedepot.com/",
  "Content-Length":10380,
  "x-hd-dc":"origin",
  "apollographql-client-version":"0.0.0",
  "X-Api-Cookies":"{\"x-user-id\":\"3091817c-69d5-3846-7d61-1d1b0acef272\"}",
  "X-current-url":"/b/Furniture-Living-Room-Furniture/N-5yc1vZc7p3",
  "X-Experience-Name":"hd-home",
  "apollographql-client-name":"hd-home",
  "x-debug":"false"
},
2:{
  "Content-Type":"application/json",
  "Accept":"*/*",
  "Accept-Language":"en-US,en;q=0.9",
  "Accept-Encoding":"gzip, deflate, br",
  "Host":"apionline.homedepot.com",
  "Origin":"https://www.homedepot.com",
  "User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15",
  "Connection":"keep-alive",
  "Referer":"https://www.homedepot.com/",
  "Content-Length":10380,
  "x-hd-dc":"origin",
  "apollographql-client-version":"0.0.0",
  "X-Api-Cookies":"{\"x-user-id\":\"3091817c-69d5-3846-7d61-1d1b0acef272\"}",
  "X-current-url":"/b/Furniture-Living-Room-Furniture/N-5yc1vZc7p3",
  "X-Experience-Name":"hd-home",
  "apollographql-client-name":"hd-home",
  "x-debug":"false"
},
3:{
    "Content-Type":"application/json",
    "Accept": "*/*",
    "Accept-Language":"en-US,en;q=0.9",
    "Accept-Encoding":"gzip, deflate, br",
    "Host":"apionline.homedepot.com",
    "Origin":"https://www.homedepot.com",
    "User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15",
    "Connection":"keep-alive",
    "Referer":"https://www.homedepot.com/",
    "Content-Length":"10380",
    "x-hd-dc":"origin",
    "apollographql-client-version":"0.0.0",
    "X-Api-Cookies":'{"x-user-id":"3091817c-69d5-3846-7d61-1d1b0acef272"}',
    "X-current-url":"/b/Furniture-Living-Room-Furniture/N-5yc1vZc7p3",
    "X-Experience-Name":"hd-home",
    "apollographql-client-name":"hd-home",
    "x-debug":"false"
},
4:{
    "Content-Type":"application/json",
    "Accept":"*/*",
    "Accept-Language":"en-US,en;q=0.9",
    "Accept-Encoding":"gzip, deflate, br",
    "Host":"apionline.homedepot.com",
    "Origin":"https://www.homedepot.com",
    "User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15",
    "Connection":"keep-alive",
    "Referer":"https://www.homedepot.com/",
    "Content-Length":"10380",
    "x-hd-dc":"origin",
    "apollographql-client-version":"0.0.0",
    "X-Api-Cookies":'{"x-user-id":"3091817c-69d5-3846-7d61-1d1b0acef272"}',
    "X-current-url":"/b/Furniture-Living-Room-Furniture/N-5yc1vZc7p3",
    "X-Experience-Name":"hd-home",
    "apollographql-client-name":"hd-home",
    "x-debug":"false"
}
}